[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'colorscheme iceberg'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
hook_add = 'source ~/.config/nvim/dein/plugins/telescope.lua'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.config/nvim/dein/plugins/lualine.lua'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = 'source ~/.config/nvim/dein/plugins/coc.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = 'source ~/.config/nvim/dein/plugins/gitsigns.lua'

[[plugins]]
repo = 'lambdalisue/gin.vim'
hook_add = 'source ~/.config/nvim/dein/plugins/gin.lua'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'skanehira/denops-translate.vim'

