[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason-lspconfig.nvim', 'nvim-cmp', 'null-ls.nvim', 'vim-vsnip']
hook_source = 'source ~/.config/nvim/dein/plugins/lsp.lua'
on_event = 'BufReadPost'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['mason.nvim']

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_source = 'source ~/.config/nvim/dein/plugins/vsnip.lua'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git', 'Gdiffsplit', 'Gclog']

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['plenary.nvim']
hook_source = 'source ~/.config/nvim/dein/plugins/gitsigns.lua'
on_event = 'BufReadPost'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons']
hook_source = 'source ~/.config/nvim/dein/plugins/lualine.lua'
on_event = 'VimEnter'

# [[plugins]]
# repo = 'nvim-treesitter/playground'
# depends = ['nvim-treesitter']
# on_source = 'nvim-treesitter'

# ref: https://zenn.dev/mkobayashime/articles/nvim-treesitter-dein
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/dein/plugins/nvim-treesitter.lua'
on_event = 'BufRead'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
depends = ['plenary.nvim', 'nvim-web-devicons', 'nvim-treesitter']
hook_post_source = 'source ~/.config/nvim/dein/plugins/telescope.lua'
on_cmd = 'Telescope'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'windwp/nvim-autopairs'
depends = ['nvim-treesitter']
hook_post_source = 'source ~/.config/nvim/dein/plugins/nvim-autopairs.lua'
on_event = 'InsertEnter'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'InsertEnter'

[[plugins]]
repo = 'kylechui/nvim-surround'
on_event = 'BufReadPost'
hook_source = 'source ~/.config/nvim/dein/plugins/nvim-surround.lua'

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_depends = ['denops.vim']
on_cmd = ['Translate']
on_map = '<Plug>(Translate)'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = ['Qfreplace']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'sh -c "cd app && yarn install"'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']

[[plugins]]
repo = '4513ECHO/denops-gitter.vim'
on_depends = ['denops.vim']
on_path = 'gitter://'
hook_source = 'source ~/.config/nvim/dein/plugins/denops-gitter.lua'
