[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'lambdalisue/gin.vim'
on_cmd = ['Gin', 'GinBuffer', 'GinBranch', 'GinChaperon', 'GinDiff', 'GinEdit', 'GinPatch', 'GinStatus']

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['plenary.nvim']
hook_source = 'source ~/.config/nvim/dein/plugins/gitsigns.lua'
on_event = 'BufRead'

# ref: https://zenn.dev/mkobayashime/articles/nvim-treesitter-dein
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/dein/plugins/nvim-treesitter.lua'
on_event = 'BufRead'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
depends = ['plenary.nvim', 'nvim-web-devicons']
hook_post_source = 'source ~/.config/nvim/dein/plugins/telescope.lua'
on_cmd = 'Telescope'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
depends = ['telescope.nvim']
on_source = 'telescope.nvim'

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_post_source = 'source ~/.config/nvim/dein/plugins/nvim-autopairs.lua'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'ModeChanged'

[[plugins]]
repo = 'skanehira/denops-translate.vim'
depends = ['denops.vim']
on_event = 'ModeChanged'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'sh -c "cd app && yarn install"'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
