[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
depends = ['mason-lspconfig.nvim', 'nvim-cmp', 'null-ls.nvim']
hook_source = 'source ~/.config/nvim/dein/plugins/lsp.lua'
on_event = 'BufRead'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['mason.nvim']

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
depends = ['cmp-nvim-lsp', 'vim-vsnip', 'cmp-path', 'cmp-buffer']

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git', 'Gdiffsplit', 'Gclog']

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
depends = ['plenary.nvim']
hook_source = 'source ~/.config/nvim/dein/plugins/gitsigns.lua'
on_event = 'BufRead'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
depends = ['nvim-web-devicons']
hook_source = 'source ~/.config/nvim/dein/plugins/lualine.lua'
on_event = 'VimEnter'

# ref: https://zenn.dev/mkobayashime/articles/nvim-treesitter-dein
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.config/nvim/dein/plugins/nvim-treesitter.lua'
on_event = 'BufEnter'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
depends = ['plenary.nvim', 'nvim-web-devicons']
hook_post_source = 'source ~/.config/nvim/dein/plugins/telescope.lua'
on_cmd = 'Telescope'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_post_source = 'source ~/.config/nvim/dein/plugins/nvim-autopairs.lua'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'BufRead'

[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = ["Translate"]
on_map = '<Plug>(Translate)'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
build = 'sh -c "cd app && yarn install"'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
