[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'colorscheme iceberg'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
hook_add = 'source ~/.config/nvim/dein/plugins/telescope.lua'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.config/nvim/dein/plugins/lualine.lua'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = 'source ~/.config/nvim/dein/plugins/coc.lua'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'set updatetime=250'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'
