[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# repo = 'cocopon/iceberg.vim'
repo = 'arrow2nd/iceberg.vim'
rev = 'feat-nvim-treesitter'
hook_add = 'colorscheme iceberg'

# [[plugins]]
# repo = 'cocopon/pgmnt.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
