# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
proto = "ssh"

[templates]
defer = '{% for file in files %}zsh-defer source "{{ file }}"{% endfor %}'
fpath_comp = 'fpath=("{{ dir }}/completions" $fpath)'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
proto = "ssh"

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']
apply = ["defer"]
proto = "ssh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]
proto = "ssh"

[plugins.zsh-abbrev-alias]
github = "momo-lab/zsh-abbrev-alias"
proto = "ssh"

[plugins.op]
local = "~/.config/op"

[plugins.ni]
github = "azu/ni.zsh"
proto = "ssh"

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.minimal]
github = "subnixr/minimal"
proto = "ssh"

[plugins."gwt.zsh"]
github = "arrow2nd/gwt.zsh"
proto = "ssh"
