[[plugins]]
repo = "Shougo/ddu.vim"
depends = ["denops.vim"]
lua_source = """
require("config.ddu")
"""

[[plugins]]
repo = "Shougo/ddu-ui-filer"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-ui-ff"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-source-action"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-source-file"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-source-file_old"
depends = ["ddu.vim"]

[[plugins]]
repo = "matsui54/ddu-source-file_external"
depends = ["ddu.vim"]

[[plugins]]
repo = "shun/ddu-source-rg"
depends = ["ddu.vim"]

[[plugins]]
repo = "shun/ddu-source-buffer"
depends = ["ddu.vim"]

[[plugins]]
repo = "matsui54/ddu-source-help"
depends = ["ddu.vim"]

[[plugins]]
repo = "uga-rosa/ddu-source-lsp"
depends = ["ddu.vim"]

[[plugins]]
repo = "kyoh86/ddu-source-quickfix_history"
depends = ["ddu.vim"]

[[plugins]]
repo = "Omochice/ddu-source-anyjump"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-source-register"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddc-source-cmdline-history"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-filter-sorter_alpha"
depends = ["ddu.vim"]

[[plugins]]
repo = "mityu/ddu-filter-matcher_multi_regex"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-kind-file"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-kind-word"
depends = ["ddu.vim"]

[[plugins]]
repo = "ryota2357/ddu-column-icon_filename"
depends = ["ddu.vim"]

[[plugins]]
repo = "matsui54/ddu-vim-ui-select"
depends = ["ddu.vim"]

[[plugins]]
repo = "Shougo/ddu-commands.vim"
depends = ["ddu.vim"]

