[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
on_event = ["BufRead"]
lua_source = """
require("config.treesitter")
"""

[[plugins]]
repo = "thinca/vim-qfreplace"
on_cmd = ["Qfreplace"]

[[plugins]]
repo = "rhysd/git-messenger.vim"
on_cmd = ["GitMessenger"]
lua_source = """
vim.g.git_messenger_floating_win_opts = { border = "single" }
"""

[[plugins]]
repo = "folke/zen-mode.nvim"
on_cmd = ["ZenMode"]
lua_source = """
require("zen-mode").setup({
  wezterm = {
    enabled = true,
    font = "+4", -- (10% increase per step)
  },
  plugins = {
    options = {
      winborder = "none",
    },
  },
})
"""
