[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_source = 'source ~/.config/nvim/dein/plugins/nvim-cmp.lua'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_source = 'source ~/.config/nvim/dein/plugins/vsnip.lua'
