[feature]
  main_user = "arrow_2nd"
  load_tweets_limit = 50
  accmulate_tweets_limit = 250
  use_external_editor = false
  is_locale_cjk = true
  startup_cmds = ["home", "mention --unfocus", "list imas 1478216622016188419 --unfocus"]

[comfirm]
  block = true
  delete = true
  follow = true
  like = true
  mute = true
  quit = true
  retweet = true
  tweet = true
  unblock = true
  unfollow = true
  unlike = true
  unmute = true
  unretweet = true

[appearance]
  style_file = "style_iceberg.toml"
  date_fmt = "2006/01/02"
  time_fmt = "15:04:05"
  user_bio_max_row = 3
  user_profile_padding_x = 4
  user_detail_separator = " | "
  hide_tweet_separator = false
  hide_quote_tweet_separator = false
  tweet_separator = "─"
  quote_tweet_separator = "-"
  graph_char = "█"
  graph_max_width = 30
  tab_separator = "|"
  tab_max_width = 20

[layout]
  tweet = "{annotation}\n{user_info}\n{text}\n{poll}\n{detail}"
  tweet_anotation = "{text} {author_name} {author_username}"
  tweet_detail = "{created_at} | via {via}\n{metrics}"
  tweet_poll = "{graph}\n{detail}"
  tweet_poll_graph = "{label}\n{graph} {per} {votes}"
  tweet_poll_detail = "{status} | {all_votes} votes | ends on {end_date}"
  user = "{user_info}\n{bio}\n{user_detail}"
  user_info = "{name} {username} {badge}"

[text]
  like = "Like"
  retweet = "RT"
  loading = "Loading..."
  no_tweets = "No tweets ฅ^-ω-^ฅ"
  tweet_textarea_hint = "What's happening?"
  tab_home = "Home"
  tab_mention = "Mention"
  tab_list = "{name}"
  tab_user = "@{name}"
  tab_search = "'{query}'"
  tab_likes = "Likes: @{name}"
  tab_docs = "?{name}"

[icon]
  geo = ""
  link = ""
  pinned = ""
  verified = ""
  private = ""

[keybinding]
  [keybinding.global]
    quit = ["ctrl+q"]
  [keybinding.view]
    close_page = ["ctrl+w"]
    focus_cmdline = [":"]
    redraw = ["ctrl+l"]
    select_next_tab = ["l", "Right"]
    select_prev_tab = ["h", "Left"]
    show_help = ["?"]
  [keybinding.page]
    reload_page = ["."]
  [keybinding.home_timeline]
    stream_mode_start = ["s"]
    stream_mode_stop = ["S"]
  [keybinding.tweet]
    copy_url = ["c"]
    cursor_bottom = ["G", "End"]
    cursor_down = ["j", "Down"]
    cursor_top = ["g", "Home"]
    cursor_up = ["k", "Up"]
    open_browser = ["o"]
    open_user_likes = ["I"]
    open_user_page = ["i"]
    quote = ["q"]
    reply = ["r"]
    scroll_down = ["alt+k", "PageDown"]
    scroll_up = ["alt+j", "PageUp"]
    tweet = ["n"]
    tweet_delete = ["D"]
    tweet_like = ["f"]
    tweet_retweet = ["t"]
    tweet_unlike = ["F"]
    tweet_unretweet = ["T"]
    user_block = ["x"]
    user_follow = ["w"]
    user_mute = ["u"]
    user_unblock = ["X"]
    user_unfollow = ["W"]
    user_unmute = ["U"]
